/*
SELECT
    'drop table '||TABLE_NAME||' cascade constraints;'
FROM
    USER_TABLES;
*/

CREATE TABLE FILIALE (
    ID_FILIALE INTEGER,
    NOME_FILIALE VARCHAR2(50) NOT NULL,
    INDIRIZZO_FILIALE VARCHAR2(100) NOT NULL,
    TELEFONO CHAR(20) NOT NULL,
    RESPONSABILE VARCHAR2(30) NOT NULL,
    CONSTRAINT P_ID_FILIALE PRIMARY KEY (ID_FILIALE)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INTEGER,
    ID_FILIALE INTEGER NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    COGNOME VARCHAR2(30) NOT NULL,
    DATA_NASCITA DATE NOT NULL,
    INDIRIZZO VARCHAR2(100) NOT NULL,
    CONSTRAINT P_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT R_ID_FILIALE FOREIGN KEY (ID_FILIALE) REFERENCES FILIALE(ID_FILIALE)
);

CREATE TABLE INVESTIMENTO (
    ID_INVESTIMENTO INTEGER,
    ID_CLIENTE INTEGER NOT NULL,
    TIPO_INVESTIMENTO VARCHAR2(30) NOT NULL,
    IMPORTO_INVESTITO NUMBER(38, 2) NOT NULL,
    DATA_INVESTIMENTO DATE NOT NULL,
    CONSTRAINT P_ID_INVESTIMENTO PRIMARY KEY (ID_INVESTIMENTO),
    CONSTRAINT R_INVESTIMENTO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE CONTO (
    NUMERO_CONTO INTEGER,
    ID_CLIENTE INTEGER NOT NULL,
    TIPO_CONTO VARCHAR2(30) NOT NULL,
    SALDO NUMBER(38, 2) NOT NULL,
    DATA_APERTURA DATE NOT NULL,
    CONSTRAINT P_NUMERO_CONTO PRIMARY KEY (NUMERO_CONTO),
    CONSTRAINT R_CONTO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE CAMBIO_VALUTA (
    ID_CAMBIO INTEGER,
    VALUTA_ORIGINE VARCHAR2(30) NOT NULL,
    VALUTA_DESTINAZIONE VARCHAR2(30) NOT NULL,
    TASSO_CAMBIO NUMBER(4, 2),
    DATA_CAMBIO DATE NOT NULL,
    CONSTRAINT P_ID_CAMBIO PRIMARY KEY (ID_CAMBIO)
);

CREATE TABLE TRANSAZIONE (
    ID_TRANSAZIONE INTEGER,
    NUMERO_CONTO INTEGER NOT NULL,
    ID_CAMBIO INTEGER NULL,
    DATA_TRANSAZIONE DATE NOT NULL,
    TIPO_TRANSAZIONE VARCHAR2(30) NOT NULL,
    IMPORTO NUMBER(38, 2) NOT NULL,
    CONSTRAINT P_ID_TRANSAZIONE PRIMARY KEY (ID_TRANSAZIONE),
    CONSTRAINT R_TRANSAZIONE_NUMERO_CONTO FOREIGN KEY (NUMERO_CONTO) REFERENCES CONTO(NUMERO_CONTO),
    CONSTRAINT R_ID_CAMBIO FOREIGN KEY (ID_CAMBIO) REFERENCES CAMBIO_VALUTA(ID_CAMBIO)
);

CREATE TABLE TASSO_INTERESSE (
    ID_TASSO INTEGER,
    TIPO_CONTO VARCHAR(30) NOT NULL,
    TASSO_ANNUO NUMBER(4, 2) NOT NULL,
    DATA_INIZIO_VALENZA DATE NOT NULL,
    DATA_FINE_VALENZA DATE NOT NULL,
    CONSTRAINT P_ID_TASSO PRIMARY KEY (ID_TASSO)
);

CREATE TABLE PRESTITO (
    ID_PRESTITO INTEGER,
    NUMERO_CONTO INTEGER NOT NULL,
    ID_TASSO INTEGER NOT NULL,
    NUMERO_PRESTITO INTEGER NOT NULL,
    IMPORTO_PRESTITO NUMBER(38, 2) NOT NULL,
    DATA_CONCESSIONE DATE NOT NULL,
    CONSTRAINT P_ID_PRESTITO PRIMARY KEY (ID_PRESTITO),
    CONSTRAINT R_PRESTITO_NUMERO_CONTO FOREIGN KEY (NUMERO_CONTO) REFERENCES CONTO(NUMERO_CONTO),
    CONSTRAINT R_ID_TASSO FOREIGN KEY (ID_TASSO) REFERENCES TASSO_INTERESSE(ID_TASSO)
);

CREATE TABLE DIPENDENTE (
    ID_DIPENDENTE INTEGER,
    ID_FILIALE INTEGER NOT NULL,
    NOME_DIPENDENTE VARCHAR2(30) NOT NULL,
    COGNOME_DIPENDENTE VARCHAR(30) NOT NULL,
    RUOLO VARCHAR2(30) NOT NULL,
    CONSTRAINT P_ID_DIPENDENTE PRIMARY KEY (ID_DIPENDENTE),
    CONSTRAINT R_DIPENDENTE_ID_FILIALE FOREIGN KEY (ID_FILIALE) REFERENCES FILIALE(ID_FILIALE)
);

CREATE TABLE BANCOMAT (
    NUMERO_BANCOMAT INTEGER,
    ID_FILIALE INTEGER NOT NULL,
    POSIZIONE VARCHAR2(100) NOT NULL,
    DATA_INSTALLAZIONE DATE NOT NULL,
    CONSTRAINT P_NUMERO_BANCOMAT PRIMARY KEY (NUMERO_BANCOMAT),
    CONSTRAINT R_BANCOMAT_ID_FILIALE FOREIGN KEY (ID_FILIALE) REFERENCES FILIALE(ID_FILIALE)
);